#!/bin/bash - 
#===============================================================================
#
#          FILE: lphkill.sh
# 
#         USAGE: ./lphkill.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Penghui Li (Penghui), 
#  ORGANIZATION: 
#       CREATED: 09/01/19 12:03:33
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

if [[ ( $# == 0 || $1 == "-h" || $1 == "--help" ) ]]; then
    echo "Usage: lphkill <key word>"
else
    kill -SIGKILL $(ps aux | grep $USER | grep -e $1 | awk '{print $2}') # delete $USER processes
fi


